// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'firebase-api-key-placeholder',
    appId: '1:975666203662:web:75e8ffc66e6340bf32005f',
    messagingSenderId: '975666203662',
    projectId: 'adfoot-production',
    authDomain: 'adfoot-production.firebaseapp.com',
    storageBucket: 'adfoot-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'firebase-api-key-placeholder',
    appId: '1:975666203662:android:b83dd7a29d1dcd5932005f',
    messagingSenderId: '975666203662',
    projectId: 'adfoot-production',
    storageBucket: 'adfoot-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'firebase-api-key-placeholder',
    appId: '1:975666203662:ios:5b190f523fd66f8632005f',
    messagingSenderId: '975666203662',
    projectId: 'adfoot-production',
    storageBucket: 'adfoot-production.firebasestorage.app',
    iosBundleId: 'org.adfoot.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'firebase-api-key-placeholder',
    appId: '1:975666203662:ios:5b190f523fd66f8632005f',
    messagingSenderId: '975666203662',
    projectId: 'adfoot-production',
    storageBucket: 'adfoot-production.firebasestorage.app',
    iosBundleId: 'org.adfoot.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'firebase-api-key-placeholder',
    appId: '1:975666203662:web:75e8ffc66e6340bf32005f',
    messagingSenderId: '975666203662',
    projectId: 'adfoot-production',
    authDomain: 'adfoot-production.firebaseapp.com',
    storageBucket: 'adfoot-production.firebasestorage.app',
  );
}
