// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _placeholderApiKey = 'firebase-api-key-placeholder';
  static const String _placeholderAppId = 'firebase-app-id-placeholder';
  static const String _placeholderSenderId = 'firebase-sender-id-placeholder';
  static const String _placeholderProjectId = 'firebase-project-placeholder';
  static const String _placeholderAuthDomain =
      'firebase-project-placeholder.firebaseapp.com';
  static const String _placeholderStorageBucket =
      'firebase-project-placeholder.firebasestorage.app';
  static const String _placeholderBundleId = 'org.adfoot.app.placeholder';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: _placeholderApiKey,
    appId: _placeholderAppId,
    messagingSenderId: _placeholderSenderId,
    projectId: _placeholderProjectId,
    authDomain: _placeholderAuthDomain,
    storageBucket: _placeholderStorageBucket,
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _placeholderApiKey,
    appId: _placeholderAppId,
    messagingSenderId: _placeholderSenderId,
    projectId: _placeholderProjectId,
    storageBucket: _placeholderStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: _placeholderApiKey,
    appId: _placeholderAppId,
    messagingSenderId: _placeholderSenderId,
    projectId: _placeholderProjectId,
    storageBucket: _placeholderStorageBucket,
    iosBundleId: _placeholderBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: _placeholderApiKey,
    appId: _placeholderAppId,
    messagingSenderId: _placeholderSenderId,
    projectId: _placeholderProjectId,
    storageBucket: _placeholderStorageBucket,
    iosBundleId: _placeholderBundleId,
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: _placeholderApiKey,
    appId: _placeholderAppId,
    messagingSenderId: _placeholderSenderId,
    projectId: _placeholderProjectId,
    authDomain: _placeholderAuthDomain,
    storageBucket: _placeholderStorageBucket,
  );
}
