param(
    [ValidateSet("local", "staging", "production")]
    [string]$Environment = "production",

    [switch]$ReleaseGate,
    [switch]$RequirePodfile,
    [switch]$RequireEntitlements,
    [switch]$RequireAssociatedDomains,
    [switch]$RequireNativeFirebase
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($ReleaseGate) {
    if (-not $PSBoundParameters.ContainsKey("RequirePodfile")) {
        $RequirePodfile = $true
    }
    if (-not $PSBoundParameters.ContainsKey("RequireEntitlements")) {
        $RequireEntitlements = $true
    }
    if (-not $PSBoundParameters.ContainsKey("RequireAssociatedDomains")) {
        $RequireAssociatedDomains = $true
    }
    if (-not $PSBoundParameters.ContainsKey("RequireNativeFirebase")) {
        $RequireNativeFirebase = $true
    }
}

function Get-PlannedBundleId {
    param(
        [Parameter(Mandatory = $true)]
        [string]$EnvironmentName
    )

    switch ($EnvironmentName) {
        "local" { return "org.adfoot.app.local" }
        "staging" { return "org.adfoot.app.staging" }
        default { return "org.adfoot.app" }
    }
}

function Get-PlistStringValue {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        [Parameter(Mandatory = $true)]
        [string]$Key
    )

    $content = Get-Content -LiteralPath $Path -Raw
    $options = [System.Text.RegularExpressions.RegexOptions]::IgnoreCase -bor
        [System.Text.RegularExpressions.RegexOptions]::Singleline
    $pattern = "<key>\s*$Key\s*</key>\s*<string>\s*([^<]+)\s*</string>"
    $match = [regex]::Match($content, $pattern, $options)

    if ($match.Success) {
        return $match.Groups[1].Value.Trim()
    }

    return $null
}

$warnings = New-Object System.Collections.Generic.List[string]
$errors = New-Object System.Collections.Generic.List[string]

$repoRoot = Split-Path -Parent $PSScriptRoot
$expectedBundleId = Get-PlannedBundleId -EnvironmentName $Environment

$workspacePath = Join-Path $repoRoot "ios/Runner.xcworkspace"
$projectPath = Join-Path $repoRoot "ios/Runner.xcodeproj/project.pbxproj"
$infoPlistPath = Join-Path $repoRoot "ios/Runner/Info.plist"
$entitlementsPath = Join-Path $repoRoot "ios/Runner/Runner.entitlements"
$podfilePath = Join-Path $repoRoot "ios/Podfile"
$podfileLockPath = Join-Path $repoRoot "ios/Podfile.lock"
$debugXcconfigPath = Join-Path $repoRoot "ios/Flutter/Debug.xcconfig"
$releaseXcconfigPath = Join-Path $repoRoot "ios/Flutter/Release.xcconfig"
$appleAssociationPath = Join-Path $repoRoot "site_pub/.well-known/apple-app-site-association"
$environmentFirebasePath = Join-Path $repoRoot "ios/Firebase/$Environment/GoogleService-Info.plist"

foreach ($requiredPath in @($workspacePath, $projectPath, $infoPlistPath, $debugXcconfigPath, $releaseXcconfigPath)) {
    if (-not (Test-Path -LiteralPath $requiredPath)) {
        $errors.Add("Missing required iOS file: $requiredPath")
    }
}

if ($RequirePodfile -and -not (Test-Path -LiteralPath $podfilePath)) {
    $errors.Add("Missing iOS Podfile: $podfilePath")
} elseif (-not (Test-Path -LiteralPath $podfilePath)) {
    $warnings.Add("Missing iOS Podfile: $podfilePath")
}

if (-not (Test-Path -LiteralPath $podfileLockPath)) {
    $warnings.Add("Podfile.lock not found. It will be generated by 'pod install' on macOS.")
}

if ($errors.Count -eq 0) {
    $projectRaw = Get-Content -LiteralPath $projectPath -Raw
    $infoDisplayName = Get-PlistStringValue -Path $infoPlistPath -Key "CFBundleDisplayName"
    $infoBundleName = Get-PlistStringValue -Path $infoPlistPath -Key "CFBundleName"

    if ($infoDisplayName -ne "Adfoot") {
        $errors.Add("CFBundleDisplayName is '$infoDisplayName' but expected 'Adfoot'.")
    }

    if ($infoBundleName -ne "Adfoot") {
        $errors.Add("CFBundleName is '$infoBundleName' but expected 'Adfoot'.")
    }

    foreach ($bundleId in @("org.adfoot.app.local", "org.adfoot.app.staging", "org.adfoot.app")) {
        if ($projectRaw -notmatch [regex]::Escape("PRODUCT_BUNDLE_IDENTIFIER = $bundleId;")) {
            $errors.Add("Missing PRODUCT_BUNDLE_IDENTIFIER '$bundleId' in Xcode project.")
        }
    }

    if ($projectRaw -notmatch [regex]::Escape("PRODUCT_BUNDLE_IDENTIFIER = $expectedBundleId;")) {
        $errors.Add("Expected bundle ID '$expectedBundleId' is not present in Xcode project.")
    }
}

foreach ($scheme in @("local", "staging", "production")) {
    $schemePath = Join-Path $repoRoot "ios/Runner.xcodeproj/xcshareddata/xcschemes/$scheme.xcscheme"
    if (-not (Test-Path -LiteralPath $schemePath)) {
        $errors.Add("Missing iOS shared scheme: $schemePath")
    }
}

foreach ($environmentName in @("local", "staging", "production")) {
    foreach ($kind in @("Debug", "Profile", "Release")) {
        $xcconfigPath = Join-Path $repoRoot "ios/Flutter/$kind-$environmentName.xcconfig"
        if (-not (Test-Path -LiteralPath $xcconfigPath)) {
            $errors.Add("Missing iOS xcconfig: $xcconfigPath")
        }
    }
}

if (Test-Path -LiteralPath $debugXcconfigPath) {
    $debugXcconfigRaw = Get-Content -LiteralPath $debugXcconfigPath -Raw
    if ($debugXcconfigRaw -notmatch 'CODE_SIGN_ENTITLEMENTS\s*=\s*Runner/Runner\.entitlements') {
        $message = "Debug.xcconfig does not set CODE_SIGN_ENTITLEMENTS=Runner/Runner.entitlements."
        if ($RequireEntitlements) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }
}

if (Test-Path -LiteralPath $releaseXcconfigPath) {
    $releaseXcconfigRaw = Get-Content -LiteralPath $releaseXcconfigPath -Raw
    if ($releaseXcconfigRaw -notmatch 'CODE_SIGN_ENTITLEMENTS\s*=\s*Runner/Runner\.entitlements') {
        $message = "Release.xcconfig does not set CODE_SIGN_ENTITLEMENTS=Runner/Runner.entitlements."
        if ($RequireEntitlements) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }
}

if (Test-Path -LiteralPath $entitlementsPath) {
    $entitlementsRaw = Get-Content -LiteralPath $entitlementsPath -Raw

    if ($entitlementsRaw -notmatch 'com\.apple\.developer\.associated-domains') {
        $message = "Runner.entitlements does not define associated domains capability."
        if ($RequireAssociatedDomains) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }

    if ($entitlementsRaw -notmatch 'applinks:adfoot\.org') {
        $message = "Runner.entitlements does not include 'applinks:adfoot.org'."
        if ($RequireAssociatedDomains) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }

    if ($entitlementsRaw -notmatch 'aps-environment') {
        $warnings.Add(
            "Runner.entitlements does not contain aps-environment. If push is enabled, verify entitlement in Xcode signing."
        )
    }
} else {
    $message = "Missing iOS entitlements file: $entitlementsPath"
    if ($RequireEntitlements) {
        $errors.Add($message)
    } else {
        $warnings.Add($message)
    }
}

if (Test-Path -LiteralPath $environmentFirebasePath) {
    $iosFirebaseBundle = Get-PlistStringValue -Path $environmentFirebasePath -Key "BUNDLE_ID"
    if (-not [string]::IsNullOrWhiteSpace($iosFirebaseBundle) -and $iosFirebaseBundle -ne $expectedBundleId) {
        $errors.Add(
            "iOS native Firebase bundle for '$Environment' is '$iosFirebaseBundle' but expected '$expectedBundleId'."
        )
    }
} else {
    $message = "Missing iOS Firebase config for '$Environment': $environmentFirebasePath"
    if ($RequireNativeFirebase) {
        $errors.Add($message)
    } else {
        $warnings.Add($message)
    }
}

if (Test-Path -LiteralPath $appleAssociationPath) {
    $appleAssociationRaw = Get-Content -LiteralPath $appleAssociationPath -Raw
    if ($appleAssociationRaw -notmatch 'org\.adfoot\.app') {
        $message = "apple-app-site-association does not reference org.adfoot.app."
        if ($RequireAssociatedDomains) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }

    if ($appleAssociationRaw -match 'TEAMID') {
        $message = "apple-app-site-association still contains TEAMID placeholder."
        if ($RequireAssociatedDomains) {
            $errors.Add($message)
        } else {
            $warnings.Add($message)
        }
    }
} else {
    $message = "Missing apple-app-site-association file: $appleAssociationPath"
    if ($RequireAssociatedDomains) {
        $errors.Add($message)
    } else {
        $warnings.Add($message)
    }
}

Write-Host "Environment                    : $Environment"
Write-Host "Expected bundle ID             : $expectedBundleId"
Write-Host "Release gate mode              : $ReleaseGate"
Write-Host "Require Podfile                : $RequirePodfile"
Write-Host "Require entitlements           : $RequireEntitlements"
Write-Host "Require associated domains     : $RequireAssociatedDomains"
Write-Host "Require native Firebase config : $RequireNativeFirebase"

if ($warnings.Count -gt 0) {
    Write-Host ""
    Write-Host "Warnings:"
    foreach ($warning in $warnings) {
        Write-Host "- $warning"
    }
}

if ($errors.Count -gt 0) {
    Write-Host ""
    Write-Host "Errors:"
    foreach ($errorMessage in $errors) {
        Write-Host "- $errorMessage"
    }
    exit 1
}

Write-Host ""
Write-Host "iOS release readiness check completed."
exit 0
